# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt install golang-1.10-go
  displayName: 'Install Golang'

- script: |
    /usr/lib/go-1.10/bin/go build
    du -sh redshift
  displayName: 'Build project'
